export default{
    name:'projects',
    title:'Projects',
    type:'document',
    fields:[
        {
            name:'name',
            title:'Title',
            type:'string'
        },
        {
            name:'description',
            title:'Description',
            type:'string'
        },
        {
            name:'imageurl',
            title:'ImageURL',
            type:'image',
            options:{
                hotspot:true,
            }
        },
        {
            name:'github',
            title:'Github',
            type:'string'
        },
        {
            name:'livedemo',
            title:'LiveDemo',
            type:'string'
        },
        {
            name:'rank',
            title:'Rank',
            type:"number"
        }
    ]
}